export interface ToolConfig {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  href: string;
  category: string;
}

export const tools: ToolConfig[] = [
  // ============================================================
  // PDF TOOLS
  // ============================================================
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one document",
    icon: "Layers",
    color: "from-red-500 to-rose-600",
    href: "/tools/merge",
    category: "pdf",
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Split a PDF into multiple files",
    icon: "Scissors",
    color: "from-orange-500 to-amber-600",
    href: "/tools/split",
    category: "pdf",
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce PDF file size",
    icon: "Minimize2",
    color: "from-green-500 to-emerald-600",
    href: "/tools/compress",
    category: "pdf",
  },
  {
    id: "extract-pages",
    name: "Extract Pages",
    description: "Extract specific pages from a PDF",
    icon: "FileOutput",
    color: "from-amber-500 to-yellow-600",
    href: "/tools/extract-pages",
    category: "pdf",
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate pages in any direction",
    icon: "RotateCw",
    color: "from-teal-500 to-cyan-600",
    href: "/tools/rotate",
    category: "pdf",
  },
  {
    id: "watermark",
    name: "Watermark PDF",
    description: "Add text or image watermarks",
    icon: "Stamp",
    color: "from-pink-500 to-rose-600",
    href: "/tools/watermark",
    category: "pdf",
  },
  {
    id: "page-numbers",
    name: "Add Page Numbers",
    description: "Insert page numbers on every page",
    icon: "Hash",
    color: "from-violet-500 to-purple-600",
    href: "/tools/page-numbers",
    category: "pdf",
  },
  {
    id: "crop-pdf",
    name: "Crop PDF",
    description: "Crop page margins and whitespace",
    icon: "Crop",
    color: "from-lime-500 to-green-600",
    href: "/tools/crop-pdf",
    category: "pdf",
  },
  {
    id: "sign-pdf",
    name: "Sign PDF",
    description: "Draw your signature on a PDF",
    icon: "PenTool",
    color: "from-blue-500 to-indigo-600",
    href: "/tools/sign-pdf",
    category: "pdf",
  },
  {
    id: "protect-pdf",
    name: "Protect PDF",
    description: "Add password protection",
    icon: "Lock",
    color: "from-red-600 to-red-700",
    href: "/tools/protect-pdf",
    category: "pdf",
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection",
    icon: "Unlock",
    color: "from-emerald-500 to-green-600",
    href: "/tools/unlock-pdf",
    category: "pdf",
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert PDF pages to PNG or JPG",
    icon: "Image",
    color: "from-blue-500 to-cyan-600",
    href: "/tools/pdf-to-image",
    category: "pdf",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF to editable .docx document",
    icon: "FileText",
    color: "from-blue-600 to-blue-800",
    href: "/tools/pdf-to-word",
    category: "pdf",
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tables from PDF as CSV",
    icon: "Table",
    color: "from-green-600 to-emerald-700",
    href: "/tools/pdf-to-excel",
    category: "pdf",
  },
  {
    id: "pdf-to-ppt",
    name: "PDF to PowerPoint",
    description: "Convert PDF pages to PPTX slides",
    icon: "FileText",
    color: "from-orange-500 to-red-600",
    href: "/tools/pdf-to-ppt",
    category: "pdf",
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert images to a PDF document",
    icon: "FileImage",
    color: "from-purple-500 to-violet-600",
    href: "/tools/image-to-pdf",
    category: "pdf",
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert HTML code to PDF",
    icon: "Globe",
    color: "from-sky-500 to-blue-600",
    href: "/tools/html-to-pdf",
    category: "pdf",
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel/CSV to formatted PDF table",
    icon: "Table",
    color: "from-green-500 to-emerald-600",
    href: "/tools/excel-to-pdf",
    category: "pdf",
  },
  {
    id: "pipeline",
    name: "Pipeline Builder",
    description: "Chain multiple PDF operations in one workflow",
    icon: "Workflow",
    color: "from-indigo-500 to-purple-600",
    href: "/tools/pipeline",
    category: "pdf",
  },
  {
    id: "scan-to-pdf",
    name: "Scan to PDF",
    description: "Scan documents with camera — auto-enhance to clean PDF",
    icon: "ScanLine",
    color: "from-slate-700 to-slate-900",
    href: "/tools/scan-to-pdf",
    category: "pdf",
  },

  // ============================================================
  // IMAGE TOOLS
  // ============================================================
  {
    id: "bg-remover",
    name: "Background Remover",
    description: "Remove image background instantly — download as transparent PNG",
    icon: "Eraser",
    color: "from-rose-500 to-purple-600",
    href: "/tools/bg-remover",
    category: "image",
  },
  {
    id: "image-upscaler",
    name: "AI Image Enhancer",
    description: "Enhance blurry/low-res images — AI upscale 2x without changing faces",
    icon: "Sparkles",
    color: "from-amber-500 to-yellow-500",
    href: "/tools/image-upscaler",
    category: "image",
  },
  {
    id: "image-resize",
    name: "Resize Image",
    description: "Resize to exact dimensions or percentage",
    icon: "Scaling",
    color: "from-fuchsia-500 to-pink-600",
    href: "/tools/image-resize",
    category: "image",
  },
  {
    id: "image-compress",
    name: "Compress Image",
    description: "Reduce file size with quality control",
    icon: "FileDown",
    color: "from-emerald-500 to-teal-600",
    href: "/tools/image-compress",
    category: "image",
  },
  {
    id: "image-crop",
    name: "Crop Image",
    description: "Crop to custom dimensions",
    icon: "CropIcon",
    color: "from-orange-500 to-red-600",
    href: "/tools/image-crop",
    category: "image",
  },
  {
    id: "image-convert",
    name: "Convert Image",
    description: "Convert between PNG, JPG, WebP",
    icon: "RefreshCw",
    color: "from-cyan-500 to-blue-600",
    href: "/tools/image-convert",
    category: "image",
  },
  {
    id: "passport-photo",
    name: "Passport Photo Maker",
    description: "Create passport-size photos (Indian standard)",
    icon: "UserSquare",
    color: "from-blue-600 to-blue-800",
    href: "/tools/passport-photo",
    category: "image",
  },
  {
    id: "image-rotate",
    name: "Rotate & Flip Image",
    description: "Rotate or flip images in any direction",
    icon: "RotateCw",
    color: "from-indigo-500 to-blue-600",
    href: "/tools/image-rotate",
    category: "image",
  },
  {
    id: "image-watermark",
    name: "Watermark Image",
    description: "Add tiled text watermark to images",
    icon: "Stamp",
    color: "from-pink-400 to-rose-500",
    href: "/tools/image-watermark",
    category: "image",
  },
  {
    id: "image-to-base64",
    name: "Image to Base64",
    description: "Convert image to Base64 data URI",
    icon: "Binary",
    color: "from-slate-500 to-gray-700",
    href: "/tools/image-to-base64",
    category: "image",
  },

  // ============================================================
  // OCR & TEXT EXTRACTION
  // ============================================================
  {
    id: "ocr",
    name: "Image to Text (OCR)",
    description: "Extract formatted text from images with paragraph detection",
    icon: "ScanText",
    color: "from-violet-600 to-indigo-700",
    href: "/tools/ocr",
    category: "ocr",
  },
  {
    id: "pdf-ocr",
    name: "PDF OCR",
    description: "Extract text from scanned PDF documents",
    icon: "FileSearch",
    color: "from-indigo-500 to-violet-600",
    href: "/tools/pdf-ocr",
    category: "ocr",
  },
  {
    id: "batch-ocr",
    name: "Batch OCR",
    description: "Process multiple images at once, download as text files",
    icon: "FolderSearch",
    color: "from-purple-500 to-indigo-600",
    href: "/tools/batch-ocr",
    category: "ocr",
  },
  {
    id: "receipt-scanner",
    name: "Receipt Scanner",
    description: "Extract amounts, dates, items from receipts & invoices",
    icon: "ReceiptText",
    color: "from-emerald-500 to-teal-600",
    href: "/tools/receipt-scanner",
    category: "ocr",
  },
  {
    id: "table-ocr",
    name: "Table Extractor",
    description: "Extract tables from images and export as CSV/Excel",
    icon: "Table",
    color: "from-blue-500 to-sky-600",
    href: "/tools/table-ocr",
    category: "ocr",
  },

  // ============================================================
  // DOCUMENT & PRESENTATION TOOLS
  // ============================================================
  {
    id: "doc-formatter",
    name: "Document Formatter",
    description: "Auto-format Word docs — fix fonts, spacing, margins in one click",
    icon: "Wand2",
    color: "from-amber-500 to-orange-600",
    href: "/tools/doc-formatter",
    category: "documents",
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert .docx Word documents to PDF",
    icon: "FileText",
    color: "from-blue-600 to-blue-800",
    href: "/tools/word-to-pdf",
    category: "documents",
  },
  {
    id: "ppt-to-pdf",
    name: "PPT to PDF",
    description: "Convert PowerPoint slides to PDF",
    icon: "FileText",
    color: "from-orange-500 to-red-500",
    href: "/tools/ppt-to-pdf",
    category: "documents",
  },
  {
    id: "ppt-to-images",
    name: "PPT to Images",
    description: "Export slides as PNG images",
    icon: "Image",
    color: "from-orange-400 to-amber-500",
    href: "/tools/ppt-to-images",
    category: "documents",
  },
  {
    id: "ppt-compress",
    name: "Compress PPT",
    description: "Reduce PowerPoint file size",
    icon: "Minimize2",
    color: "from-orange-600 to-red-600",
    href: "/tools/ppt-compress",
    category: "documents",
  },
  {
    id: "ppt-merge",
    name: "Merge PPT",
    description: "Combine multiple presentations",
    icon: "Layers",
    color: "from-red-400 to-orange-500",
    href: "/tools/ppt-merge",
    category: "documents",
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, reading time",
    icon: "TextCursorInput",
    color: "from-blue-500 to-indigo-600",
    href: "/tools/word-counter",
    category: "documents",
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text case: UPPER, lower, Title",
    icon: "CaseSensitive",
    color: "from-purple-500 to-indigo-600",
    href: "/tools/case-converter",
    category: "documents",
  },
  {
    id: "text-formatter",
    name: "Text Formatter",
    description: "Format, clean, sort, and fix text",
    icon: "AlignLeft",
    color: "from-indigo-500 to-violet-600",
    href: "/tools/text-formatter",
    category: "documents",
  },
  {
    id: "find-replace",
    name: "Find & Replace",
    description: "Bulk find and replace text patterns",
    icon: "Search",
    color: "from-sky-500 to-blue-600",
    href: "/tools/find-replace",
    category: "documents",
  },
  {
    id: "remove-duplicates",
    name: "Remove Duplicates",
    description: "Remove duplicate lines from text",
    icon: "ListX",
    color: "from-rose-500 to-red-600",
    href: "/tools/remove-duplicates",
    category: "documents",
  },

  // ============================================================
  // FINANCIAL CALCULATORS
  // ============================================================
  {
    id: "emi-calculator",
    name: "EMI Calculator",
    description: "Calculate EMI for home, car, personal loans",
    icon: "IndianRupee",
    color: "from-green-600 to-emerald-700",
    href: "/tools/emi-calculator",
    category: "calculators",
  },
  {
    id: "gst-calculator",
    name: "GST Calculator",
    description: "Calculate GST (5%, 12%, 18%, 28%)",
    icon: "Receipt",
    color: "from-orange-500 to-orange-700",
    href: "/tools/gst-calculator",
    category: "calculators",
  },
  {
    id: "sip-calculator",
    name: "SIP Calculator",
    description: "Calculate SIP investment returns",
    icon: "TrendingUp",
    color: "from-blue-500 to-blue-700",
    href: "/tools/sip-calculator",
    category: "calculators",
  },

  // ============================================================
  // DEVELOPER TOOLS
  // ============================================================
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON",
    icon: "Braces",
    color: "from-yellow-500 to-amber-600",
    href: "/tools/json-formatter",
    category: "dev-tools",
  },
  {
    id: "base64",
    name: "Base64 Encode/Decode",
    description: "Encode or decode Base64 strings",
    icon: "Binary",
    color: "from-slate-600 to-gray-800",
    href: "/tools/base64",
    category: "dev-tools",
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode or decode URL parameters",
    icon: "Link",
    color: "from-blue-500 to-indigo-600",
    href: "/tools/url-encoder",
    category: "dev-tools",
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors, convert formats, generate palettes",
    icon: "Palette",
    color: "from-rose-400 to-pink-500",
    href: "/tools/color-picker",
    category: "dev-tools",
  },
  {
    id: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, UPI",
    icon: "QrCode",
    color: "from-gray-700 to-gray-900",
    href: "/tools/qr-code",
    category: "dev-tools",
  },
  {
    id: "qr-scanner",
    name: "QR & Barcode Scanner",
    description: "Scan QR codes, UPI, barcodes with camera",
    icon: "ScanLine",
    color: "from-emerald-500 to-teal-600",
    href: "/tools/qr-scanner",
    category: "dev-tools",
  },
];

export const categories = [
  { id: "all", name: "All Tools" },
  { id: "pdf", name: "PDF Tools" },
  { id: "image", name: "Image Tools" },
  { id: "ocr", name: "OCR & Text Extract" },
  { id: "documents", name: "Documents & Text" },
  { id: "calculators", name: "Calculators" },
  { id: "dev-tools", name: "Developer Tools" },
];
