export const toolContentData: Record<string, {
  title: string;
  description: string;
  howTo: string[];
  features: string[];
  faqs: { q: string; a: string }[];
}> = {
  compress: {
    title: "PDF Compressor",
    description: "Reduce the file size of your PDF documents without losing significant quality. Our PDF compressor uses Ghostscript engine for real image recompression, reducing file sizes by 40-80% for image-heavy PDFs. Perfect for email attachments, web uploads, and meeting file size requirements.",
    howTo: [
      "Upload your PDF file by dragging it into the drop zone or clicking to browse",
      "Select your compression level: Maximum (smallest file), Balanced (recommended), or Minimum (best quality)",
      "Click 'Compress PDF' and wait for processing",
      "Download your compressed PDF — check the size reduction percentage shown",
    ],
    features: [
      "Reduce PDF size by up to 80%",
      "Three compression levels to choose from",
      "Preserves text quality and readability",
      "Server-side Ghostscript compression for best results",
      "Client-side fallback if server is busy",
      "No file size limits",
      "Works with scanned PDFs and image-heavy documents",
      "Files auto-deleted from server after processing",
    ],
    faqs: [
      { q: "How much can I compress my PDF?", a: "Typically 40-80% for PDFs with images. Text-only PDFs may see 10-30% reduction since text is already compact." },
      { q: "Will compression reduce the quality of my PDF?", a: "Maximum compression reduces image DPI to ~150 which is good for screen viewing. Balanced mode (~300 DPI) keeps print quality. Minimum mode barely affects quality." },
      { q: "Is my file uploaded to a server?", a: "Yes, for optimal compression we use server-side Ghostscript processing. Your file is automatically deleted immediately after compression. If you prefer local-only processing, the tool falls back to client-side if the server is unavailable." },
      { q: "What's the maximum file size I can compress?", a: "There's no hard limit. Files up to 100MB work well. Very large files may take longer to process." },
    ],
  },
  merge: {
    title: "PDF Merger",
    description: "Combine multiple PDF files into a single document in seconds. Drag and drop your files, reorder them as needed, and merge them into one cohesive PDF. Runs entirely in your browser — your files never leave your device.",
    howTo: [
      "Upload two or more PDF files by dragging them into the drop zone",
      "Reorder files by dragging them to the desired position",
      "Click 'Merge PDFs' to combine them",
      "Download your merged PDF file",
    ],
    features: [
      "Merge unlimited PDF files at once",
      "Drag-and-drop reordering",
      "100% client-side — files never uploaded",
      "Preserves all formatting, links, and bookmarks",
      "Works with any PDF size",
      "No watermarks added",
      "Instant processing",
      "Works offline (PWA)",
    ],
    faqs: [
      { q: "How many PDFs can I merge at once?", a: "There's no limit. You can merge as many PDFs as your browser memory allows — typically 50+ files without issues." },
      { q: "Are my files uploaded anywhere?", a: "No. Merging happens 100% in your browser using pdf-lib. Your files never leave your device." },
      { q: "Will the merged PDF keep my bookmarks and links?", a: "Yes, all internal structure including hyperlinks, bookmarks, and form fields are preserved." },
      { q: "Can I merge password-protected PDFs?", a: "You'll need to unlock them first using our Unlock PDF tool, then merge the unlocked versions." },
    ],
  },
  split: {
    title: "PDF Splitter",
    description: "Split a PDF document into multiple files by page ranges or individual pages. Extract specific pages, split in half, or separate every page into its own file. All processing happens locally in your browser.",
    howTo: [
      "Upload your PDF file",
      "The tool automatically detects the total page count",
      "Select pages to extract using quick-select buttons or enter custom ranges",
      "Click 'Split PDF' to create separate files",
      "Download individual files or all as a ZIP",
    ],
    features: [
      "Split by page ranges (e.g., 1-5, 6-10)",
      "Extract individual pages",
      "Quick-select: All, First Half, Second Half, First, Last",
      "Auto-detects page count",
      "Download as ZIP for multiple files",
      "100% client-side processing",
      "Preserves page formatting",
      "No file size limits",
    ],
    faqs: [
      { q: "Can I extract non-consecutive pages?", a: "Yes, you can select any combination of pages — for example pages 1, 3, 7-10." },
      { q: "What happens to the original file?", a: "Nothing — the original stays untouched. The tool creates new PDF files from the selected pages." },
      { q: "Is there a page limit?", a: "No. The tool works with PDFs of any length." },
    ],
  },
  pdfToWord: {
    title: "PDF to Word Converter",
    description: "Convert PDF documents to editable Microsoft Word (.docx) files while preserving formatting, tables, images, and fonts. Uses CloudConvert's professional conversion engine for the highest quality output — far better than simple text extraction.",
    howTo: [
      "Upload your PDF file",
      "Click 'Convert to Word'",
      "Wait for server-side processing (typically 5-15 seconds)",
      "Download your .docx file and open in Microsoft Word or Google Docs",
    ],
    features: [
      "Preserves tables, images, and formatting",
      "Professional CloudConvert engine (Apryse technology)",
      "Handles multi-page documents",
      "Supports scanned PDFs (with embedded text)",
      "Output opens in Microsoft Word, Google Docs, LibreOffice",
      "No watermarks or branding added",
      "Files auto-deleted from server after conversion",
      "Privacy notice shown before upload",
    ],
    faqs: [
      { q: "Why does this tool upload my file?", a: "High-quality PDF to Word conversion requires server-side processing with professional engines. Simple client-side conversion would only give you plain text without formatting. We use CloudConvert's Apryse engine for best results." },
      { q: "Is my file kept on the server?", a: "No. Files are automatically deleted from CloudConvert's servers immediately after your download completes." },
      { q: "Can I convert scanned PDFs?", a: "If your PDF has embedded text (most modern scans do), yes. For image-only PDFs, use our OCR tool first to extract text, then convert." },
      { q: "How accurate is the conversion?", a: "Very accurate for standard documents. Complex layouts (multi-column, heavy graphics) may have minor differences." },
    ],
  },
  bgRemover: {
    title: "AI Background Remover",
    description: "Remove backgrounds from images instantly using AI — no manual selection needed. Our tool runs a neural network directly in your browser to detect subjects and remove backgrounds with precision. Works with portraits, products, animals, and more. Output as transparent PNG.",
    howTo: [
      "Upload an image (JPG, PNG, or WebP)",
      "The AI automatically detects the subject and removes the background",
      "Wait 5-15 seconds for processing (first use downloads a ~5MB AI model)",
      "Download your image with transparent background as PNG",
    ],
    features: [
      "AI-powered — no manual selection needed",
      "Runs entirely in your browser (no upload)",
      "Works with portraits, products, pets, objects",
      "Outputs transparent PNG",
      "Handles hair, fur, and complex edges",
      "No watermarks",
      "Unlimited uses — no daily limit",
      "First use downloads 5MB model, then works offline",
    ],
    faqs: [
      { q: "Is this really free with no limit?", a: "Yes. The AI model runs in your browser using @imgly/background-removal. There's no server cost for us, so there's no reason to limit you." },
      { q: "Does it work with product photos?", a: "Yes, it works great with product photography, portraits, animals, and any image with a clear subject." },
      { q: "Why is the first use slower?", a: "The first time you use it, the tool downloads a ~5MB neural network model. After that, it's cached and works instantly (even offline)." },
      { q: "Can I use this on mobile?", a: "Yes, it works on any device with a modern browser. Processing may take slightly longer on older phones." },
    ],
  },
  imageCompress: {
    title: "Image Compressor",
    description: "Compress and optimize images in JPEG, PNG, WebP, AVIF, HEIC/HEIF, and SVG formats. Reduce file sizes significantly while maintaining visual quality. Convert between formats, process batches, and compare before/after results. Everything runs locally — your images never leave your device.",
    howTo: [
      "Drop one or more images (or a ZIP file) into the upload area",
      "Adjust the quality slider — lower means smaller file, higher means better quality",
      "Optionally select a different output format (e.g., convert PNG to WebP)",
      "Click 'Compress' to process all images",
      "Compare before/after using the slider, then download all as ZIP",
    ],
    features: [
      "Supports JPEG, PNG, WebP, AVIF, HEIC/HEIF, SVG, GIF, BMP, TIFF",
      "PNG compression preserves transparency",
      "SVG optimization via SVGO (removes metadata, minifies paths)",
      "HEIC/HEIF decoding for iPhone photos",
      "Format conversion (any-to-any)",
      "Before/after comparison slider",
      "Batch processing with ZIP download",
      "100% local — no files uploaded",
    ],
    faqs: [
      { q: "Which format gives the smallest file?", a: "WebP typically gives 25-35% smaller files than JPEG at the same quality. AVIF is even smaller but has less browser support." },
      { q: "Will PNG compression lose my transparency?", a: "No. When compressing PNG, transparency is preserved. Only when converting to JPEG does transparency become a white background." },
      { q: "Can I compress HEIC photos from my iPhone?", a: "Yes. HEIC files are decoded locally and can be compressed or converted to JPEG/WebP/PNG." },
      { q: "Does SVG optimization change how my graphic looks?", a: "No. SVGO removes invisible metadata, unnecessary attributes, and whitespace. The visual output is identical, just a smaller file." },
    ],
  },
  ocr: {
    title: "OCR — Image to Text",
    description: "Extract text from images using Optical Character Recognition (OCR). Supports 12 languages including English, Hindi, and more. Uses Tesseract.js which runs entirely in your browser — no server upload needed. Works with photos of documents, screenshots, handwritten notes, and more.",
    howTo: [
      "Upload an image containing text (JPG, PNG, or screenshot)",
      "Select the language of the text in the image",
      "Click 'Extract Text' and wait for OCR processing",
      "Copy the extracted text or download as a text file",
    ],
    features: [
      "12 languages supported (English, Hindi, Spanish, French, German, etc.)",
      "100% client-side — images never uploaded",
      "Paragraph and formatting detection",
      "Works with photos, screenshots, scanned documents",
      "Copy to clipboard with one click",
      "Download as .txt file",
      "Confidence score shown",
      "Works offline after first model download",
    ],
    faqs: [
      { q: "How accurate is the OCR?", a: "Very accurate for printed text with good contrast. Handwritten text and low-resolution images may have lower accuracy." },
      { q: "Why does the first use take longer?", a: "Tesseract.js downloads language-specific recognition models (~2-5MB each) on first use. They're cached for subsequent uses." },
      { q: "Can it read handwritten text?", a: "It can attempt handwritten text, but accuracy varies significantly. It works best with clear, printed text." },
      { q: "Does it work with non-English text?", a: "Yes. Select the appropriate language before processing. We support 12 languages including Hindi, Arabic, Chinese, Japanese, and more." },
    ],
  },
  scanToPdf: {
    title: "Document Scanner (Scan to PDF)",
    description: "Scan physical documents using your phone or webcam camera and convert them to clean, professional PDFs. Features live camera preview, edge detection, perspective correction, image enhancement filters, and multi-page support. Works like Adobe Scan but completely free with no app download required.",
    howTo: [
      "Open the tool on your phone (works best with rear camera)",
      "Point the camera at your document",
      "Capture the image (manual button)",
      "Adjust the four corner handles to correct perspective",
      "Apply an enhancement filter (Grayscale, Black & White, or Auto-Enhance)",
      "Add more pages if needed, then export as PDF",
    ],
    features: [
      "Live camera preview (rear camera on mobile)",
      "4-corner perspective correction",
      "Image enhancement filters (Original, Grayscale, B&W, Enhanced)",
      "Multi-page document scanning",
      "Page reorder, rotate, and delete",
      "Optional OCR for searchable PDF text layer",
      "Export as high-quality PDF (A4 sizing)",
      "100% local processing — no files uploaded",
    ],
    faqs: [
      { q: "How is this different from just taking a photo?", a: "The perspective correction straightens your document (removes skew/tilt), and the enhancement filters make text crisp and clear. The output looks like a professional scan, not a phone photo." },
      { q: "Can I scan multiple pages?", a: "Yes. Scan as many pages as you need, reorder them, then export as a single multi-page PDF." },
      { q: "Does it work on desktop?", a: "Yes, if your computer has a webcam. It works best on mobile phones where you can easily photograph documents." },
      { q: "Is the PDF searchable?", a: "Enable the OCR toggle before exporting. This adds an invisible text layer so you can search and copy text from the PDF." },
    ],
  },
  passportPhoto: {
    title: "Passport Photo Maker",
    description: "Create standard passport-size photos for Indian passport, visa, and ID card applications. Automatically sizes and arranges photos on a printable sheet (A4, A5, 4x6, 5x7, or Letter). Just upload a photo with a plain background — the tool handles cropping and layout.",
    howTo: [
      "Upload a portrait photo with a plain background",
      "Adjust the crop area to center your face",
      "Select the paper size for your printer (A4, A5, 4x6, etc.)",
      "Preview the printable sheet with multiple photos arranged",
      "Download and print at actual size (no scaling)",
    ],
    features: [
      "Indian passport standard sizes (35mm x 45mm)",
      "Multiple paper sizes: A4, A5, A3, 4x6, 5x7, Letter",
      "Auto-fills entire sheet for maximum photos per page",
      "Preview before download",
      "Print at actual size — no scaling needed",
      "Works with any portrait photo",
      "100% client-side processing",
      "No watermarks",
    ],
    faqs: [
      { q: "What size photos does this create?", a: "Standard Indian passport size: 35mm x 45mm (3.5cm x 4.5cm), which is also accepted for most Indian visa and ID applications." },
      { q: "How should I take the source photo?", a: "Use a plain white or light background, face the camera directly, ensure good lighting with no shadows, and keep your face centered." },
      { q: "Can I use this for US/UK passport photos?", a: "The current version uses Indian standard sizing. US (2x2 inch) and UK (35x45mm) sizes may be added in future updates." },
    ],
  },
  signPdf: {
    title: "PDF Signature Tool",
    description: "Add your signature to PDF documents without printing. Draw your signature with mouse or touchscreen, type your name in an elegant font, or upload a pre-made signature image. Position it anywhere on the document. Perfect for contracts, forms, and official documents.",
    howTo: [
      "Upload the PDF document you need to sign",
      "Choose a signature method: Draw, Type, or Upload Image",
      "Create or select your signature",
      "Choose the position on the page (bottom-right, center, etc.)",
      "Click 'Sign & Download' to get your signed PDF",
    ],
    features: [
      "Three signature modes: Draw, Type, Upload",
      "Smooth drawing with mouse or touchscreen",
      "Elegant serif font for typed signatures",
      "Upload specimen signatures (principal, director, etc.)",
      "6 position options per page",
      "Works with any PDF",
      "100% client-side — document never uploaded",
      "No watermarks or branding",
    ],
    faqs: [
      { q: "Is this legally valid?", a: "Electronic signatures are legally recognized in many jurisdictions. However, for critical legal documents, consult with a legal professional about your jurisdiction's requirements." },
      { q: "Can I sign multiple pages?", a: "The signature is applied to the page you select. For multi-page signing, you can process the document multiple times." },
      { q: "Is my document uploaded anywhere?", a: "No. All processing happens in your browser. Your sensitive documents never leave your device." },
    ],
  },
};
